version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - connector_telegram
        - connector_slack
        - database_matrix
        - connector_matrix

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
